### ISSUE TITLE
Glonax tests

### ISSUE THREAD

**Issue by yorickdewid** [Laixer/Glonax#60]
- [x] HCU command after disconnect from network with fail safe flag and connection reset
- [x] Fuzz TCP connection, send corrupt data corpus, large payloads, double headers etc..
- [x] Open more than MAX TCP connections
- [x] Log should always show NAME information right after startup from all devices on the network that support it.
- [x] Slow down network traffic
- [x] Send invalid engine commands, RPM too high, RPM too low, etc..
- [x] Slow down CPU, check if control pipeline completes within TIMESLICE
- [x] Trigger out of memory manager, glonax should survive untill the end/last
- [x] Overload command pipeline with motion messages (queue overload)
- [x] Generate CAN traffic, trigger maximum interrupts on the hardware
- [x] Check interrupt priority when there are too many interrupts (io bound traffic)

**Comment by daan-laixer** [comment]
It takes around 16 minutes before glonax crashes (because host is not reachable is detected) when ethernet connection is physically disconnected. 

```
Jun 03 15:49:25 rpi-vms glonaxd[1331]: Accepted connection from: 10.0.20.237:51779
Jun 03 15:49:25 rpi-vms glonaxd[1331]: Active connections: 1/10
Jun 03 15:49:25 rpi-vms glonaxd[1331]: Spawning client session
Jun 03 15:49:25 rpi-vms glonaxd[1331]: Client session started
Jun 03 15:49:25 rpi-vms glonaxd[1331]: Session started for godot/4.2 with control, command, stream
Jun 03 16:03:56 rpi-vms glonaxd[1331]: [can1] laixer:hcu:0x4A: communication timeout
Jun 03 16:03:56 rpi-vms glonaxd[1331]: [can1] laixer:hcu:0x4A: communication timeout
Jun 03 16:03:56 rpi-vms glonaxd[1331]: [can1] laixer:hcu:0x4A: communication timeout
Jun 03 16:03:56 rpi-vms glonaxd[1331]: [can1] laixer:hcu:0x4A: communication timeout
Jun 03 16:03:58 rpi-vms glonaxd[1331]: [can1] laixer:hcu:0x4A: communication timeout
Jun 03 16:03:58 rpi-vms glonaxd[1331]: [can1] laixer:hcu:0x4A: communication timeout
Jun 03 16:03:58 rpi-vms glonaxd[1331]: [can1] laixer:hcu:0x4A: communication timeout
Jun 03 16:03:58 rpi-vms glonaxd[1331]: [can1] laixer:hcu:0x4A: communication timeout
Jun 03 16:05:20 rpi-vms glonaxd[1331]: thread 'tokio-runtime-worker' panicked at /home/eve/glonax/glonax-runtime/src/service/tcp_server.rs:222:71:
Jun 03 16:05:20 rpi-vms glonaxd[1331]: called `Result::unwrap()` on an `Err` value: Os { code: 113, kind: HostUnreachable, message: "No route to host" }
Jun 03 16:05:20 rpi-vms glonaxd[1331]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by daan-laixer** [comment]
The EngineState does not seem to matter, 0x00 (no_request), 0x01 (starting), 0x02 (stopping), 0x10(request), all seem to result in a rpm request

**Comment by daan-laixer** [comment]
When glonax is flooded with motion messages the buffers of multiple com devices are full:

```
Jun 05 12:02:44 rpi-vms glonaxd[7474]: [can1] laixer:hcu:0x27:0x4A: No buffer space available<4>Failed to parse frame: IO error: Failed to parse packet
Jun 05 12:02:44 rpi-vms glonaxd[7474]:  (os error 105)<4>Failed to parse frame: IO error: Failed to parse packet
Jun 05 12:02:44 rpi-vms glonaxd[7474]: <4>Failed to parse frame: IO error: Failed to parse packet
Jun 05 12:02:44 rpi-vms glonaxd[7474]: [can1] <4>Failed to parse frame: IO error: Failed to parse packet
Jun 05 12:02:44 rpi-vms glonaxd[7474]: volvo:d7e:0x27:0x0: No buffer space available (os error 105<4>Failed to parse frame: IO error: Failed to parse packet
Jun 05 12:02:44 rpi-vms glonaxd[7474]: )
Jun 05 12:02:44 rpi-vms glonaxd[7474]: [<4>Failed to parse frame: IO error: Failed to parse packet
Jun 05 12:02:44 rpi-vms glonaxd[7474]: can1] laixer:hcu:0x27:0x4A: No buffer space available (os error 105<4>Failed to parse frame: IO error: Failed to parse packet
Jun 05 12:02:44 rpi-vms glonaxd[7474]: )
Jun 05 12:02:44 rpi-vms glonaxd[7474]: [can1] volvo:d7e:0x27:0x0: No buffer space available (os error 105)
Jun 05 12:02:44 rpi-vms glonaxd[7474]: [can1] laixer:hcu:0x27:0x4A: No buffer space available (os error 105)
Jun 05 12:02:44 rpi-vms glonaxd[7474]: [can1] volvo:d7e:0x27:0x0: <4>Failed to parse frame: IO error: Failed to parse packet
Jun 05 12:02:44 rpi-vms glonaxd[7474]: No buffer space available (os error 105)<4>Failed to parse frame: IO error: Failed to parse packet
Jun 05 12:02:44 rpi-vms glonaxd[7474]: [can1] laixer:hcu:0x27:0x4A: No buffer space available (os error 105)<4>Failed to parse frame: IO error: Failed to parse packet
Jun 05 12:02:44 rpi-vms glonaxd[7474]: [can1] <4>Failed to parse frame: IO error: Failed to parse packet
Jun 05 12:02:44 rpi-vms glonaxd[7474]: volvo:d7e:0x27:0x0: No buffer space available (os error 105)
Jun 05 12:02:44 rpi-vms glonaxd[7474]: [can1] laixer:hcu:0x27:0x4A<4>Failed to parse frame: IO error: Failed to parse packet
Jun 05 12:02:44 rpi-vms glonaxd[7474]: : No buffer space available (os error 105)<4>Failed to parse frame: IO error: Failed to parse packet
Jun 05 12:02:44 rpi-vms glonaxd[7474]: [can1] volvo:d7e:0x27:0x0<4>Failed to parse frame: IO error: Failed to parse packet
Jun 05 12:02:44 rpi-vms glonaxd[7474]: : No buffer space available (os error 105)
Jun 05 12:02:44 rpi-vms glonaxd[7474]: [can1<4>Failed to parse frame: IO error: Failed to parse packet
```

**Comment by daan-laixer** [comment]
Panic spotted when running duration test sending various corrupted messages, not reproduced yet.

```
Jun 05 15:20:50 rpi-vms glonaxd[9997]: thread 'tokio-runtime-worker' panicked at /home/eve/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.6.0/src/lib.rs:137:5:
Jun 05 15:20:50 rpi-vms glonaxd[9997]: advance out of bounds: the len is 0 but advancing by 1
Jun 05 15:20:50 rpi-vms glonaxd[9997]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by daan-laixer** [comment]
The CAN network has been stressed by using the following:

On beelink:
- glonax-netctl -i can0 fuzzer 01 -i 1

On rpi:
- glonax-netctl -i can1 fuzzer 01 -i 1

Glonax ran the rpi.

Extra traffic has been observed, no effect on control pipeline.

**Comment by daan-laixer** [comment]
CPU has been tested for an extended period using:

`stress-ng --cpu 4 --timeout 1h`

CPU cores being stressed have been observed in htop, no effect on control pipeline.
